const EMPREENDIMENTOS = [
  {
    id: 'residencial-maro',
    nome: 'Residencial Maro',
    status: 'Em construção',
    slug: 'residencial-maro',
    bairro: 'Itapegica',
    cidade: 'Guarulhos - SP',
    faixaPreco: 'R$ 239.418 a R$ 381.247',
    fotoCapa: 'assets/fotos/maro/fachada.jpg?v=2',
    video: 'assets/videos/hero-video.mp4?v=2',
    corDestaque: '#084B51',
    descricaoCurta: 'Primeiro lançamento do Pátio Guarulhos by BP8. Apartamentos de 27 a 46 m² em frente ao Shopping Internacional Guarulhos, ao lado da futura Estação Dutra de metrô. Financiamento MCMV disponível.',
    descricaoCompleta: 'O Residencial Maro é o primeiro lançamento dentro do Pátio Guarulhos, novo complexo da BP8 com 6 lotes estrategicamente localizado em frente ao Shopping Internacional Guarulhos, ao lado da futura Estação Dutra de metrô e a poucos minutos do Aeroporto Internacional de Guarulhos. 19 itens de lazer e conveniência, lavanderia compartilhada OMO e apartamentos de 27 a 46 m² com financiamento Minha Casa Minha Vida. Condomínio fechado com portaria e áreas de coworking, mini mercado e espaço delivery.',
    torres: 2,
    unidades: 468,
    areaLazer: [
      'Piscina Adulto e Infantil',
      'Academia',
      'Fitness Externo',
      'Quadra',
      'Salão de Festas 01',
      'Salão de Festas 02',
      'Salão de Festas Externo',
      'Coworking',
      'Espaço Gourmet',
      'Churrasqueira 01',
      'Churrasqueira 02',
      'Sports Bar',
      'Sports Bar Externo',
      'Brinquedoteca Kids',
      'Brinquedoteca Baby',
      'Playground',
      'Pet Place',
      'Lavanderia Compartilhada',
      'Mini Mercado'
    ],
    diferenciais: [
      'Primeiro lançamento do Pátio Guarulhos by BP8',
      'Em frente ao Shopping Internacional Guarulhos',
      'Ao lado da futura Estação Dutra de metrô',
      'Fácil acesso ao Terminal de Ônibus de Guarulhos',
      'A poucos minutos do Aeroporto Internacional de Guarulhos',
      '19 itens de lazer e conveniência',
      'Minha Casa Minha Vida',
      'Lavanderia compartilhada OMO',
      'Condomínio fechado com portaria e clausura'
    ],
    localizacao: {
      embedUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3659.2428551050903!2d-46.55109997467213!3d-23.487760578850477!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x94ce5f84e39940f5%3A0x6aa97d7e8801230c!2sRua%20Engenheiro%20Camilo%20Olivetti%2056%2C%20Itapegica!5e0!3m2!1spt-BR!2sbr!4v1770049374223!5m2!1spt-BR!2sbr',
      mapsUrl: 'https://maps.app.goo.gl/YHFM6rpfCLvsH2Vg7',
      endereco: 'Av. Carlos Ferreira Endres, s/n - Itapegica. Em frente ao Shopping Internacional Guarulhos',
      mobilidade: 'Ao lado da futura Estação Dutra de metrô, fácil acesso ao Terminal de Ônibus de Guarulhos, à Via Dutra e próximo ao Aeroporto Internacional.',
      bairro: 'Itapegica'
    },
    temMCMV: true,
    plantas: [
      {
        nome: 'Tipo D - Studio',
        area: '27 m²',
        preco: 'R$ 239.418,48',
        avaliacao: 'R$ 268.905,00',
        imagem: 'assets/plantas/maro/planta-studio.jpg',
        destaque: false,
        tag: 'Studio',
        slug: 'tipo-d-studio'
      },
      {
        nome: 'Tipo A - 2 Dorms',
        area: '39,53 m²',
        preco: 'R$ 357.000',
        avaliacao: 'R$ 390.500',
        imagem: 'assets/plantas/maro/planta-2-dorms-sem-vaga.jpg',
        destaque: false,
        tag: '2 Dormitórios',
        slug: 'tipo-a-2-dorms'
      },
      {
        nome: 'Tipo C - 2 Dorms',
        area: '39,16 m²',
        preco: 'R$ 376.584,56',
        avaliacao: 'R$ 380.946,00',
        imagem: 'assets/plantas/maro/planta-2-dorms-com-vaga.jpg',
        destaque: true,
        tag: '2 Dormitórios',
        badge: 'Mais vendido',
        slug: 'tipo-c-2-dorms'
      },
      {
        nome: 'Tipo E - 2 Dorms',
        area: '39,16 m²',
        preco: 'R$ 320.178,08',
        avaliacao: 'R$ 337.755,00',
        imagem: 'assets/plantas/maro/planta-2-dorms-sem-vaga.jpg',
        destaque: false,
        tag: '2 Dormitórios',
        slug: 'tipo-e-2-dorms'
      },
      {
        nome: 'Tipo B - 2 Dormitórios',
        area: '46,40 m²',
        preco: 'R$ 381.246,72',
        avaliacao: 'R$ 425.280,00',
        imagem: 'assets/plantas/maro/planta-2-dorms-suite.jpg',
        destaque: false,
        tag: '2 Dormitórios',
        slug: 'tipo-b-2-dorms-suite'
      }
    ],
    galeria: [
      { src: 'assets/fotos/maro/galeria/01_fachada.jpeg', caption: 'Fachada Noturna' },
      { src: 'assets/fotos/maro/galeria/02_fachada2.jpeg', caption: 'Fachada' },
      { src: 'assets/fotos/maro/galeria/03_portaria.jpeg', caption: 'Portaria' },
      { src: 'assets/fotos/maro/galeria/04_salaofestas1.jpeg', caption: 'Salão de Festas 1' },
      { src: 'assets/fotos/maro/galeria/05_salaofestas2.jpeg', caption: 'Salão de Festas 2' },
      { src: 'assets/fotos/maro/galeria/06_espacogourmet.jpeg', caption: 'Espaço Gourmet' },
      { src: 'assets/fotos/maro/galeria/07_sportsbar.jpeg', caption: 'Sports Bar' },
      { src: 'assets/fotos/maro/galeria/08_brinquedotecababy.jpeg', caption: 'Brinquedoteca Baby' },
      { src: 'assets/fotos/maro/galeria/09_brinquedotecakids.jpeg', caption: 'Brinquedoteca Kids' },
      { src: 'assets/fotos/maro/galeria/10_academia.jpeg', caption: 'Academia' },
      { src: 'assets/fotos/maro/galeria/11_coworking.jpeg', caption: 'Coworking' },
      { src: 'assets/fotos/maro/galeria/12_lavanderia.jpeg', caption: 'Lavanderia' },
      { src: 'assets/fotos/maro/galeria/13_piscina.jpeg', caption: 'Piscina' },
      { src: 'assets/fotos/maro/galeria/14_petplace.jpeg', caption: 'Pet Place' },
      { src: 'assets/fotos/maro/galeria/15_playground.jpeg', caption: 'Playground' },
      { src: 'assets/fotos/maro/galeria/16_sportsbarexterno.jpeg', caption: 'Sports Bar Externo' },
      { src: 'assets/fotos/maro/galeria/17_churrasqueira2.jpeg', caption: 'Churrasqueira' },
      { src: 'assets/fotos/maro/galeria/18_fitnessexterno.jpeg', caption: 'Fitness Externo' },
      { src: 'assets/fotos/maro/galeria/19_quadra.jpeg', caption: 'Quadra Poliesportiva' }
    ]
  },
  {
    id: 'residencial-momi',
    nome: 'Residencial Momi',
    status: 'Em construção',
    slug: 'residencial-momi',
    bairro: 'Itapegica',
    cidade: 'Guarulhos - SP',
    faixaPreco: 'R$ 239.418 a R$ 381.247',
    fotoCapa: 'assets/fotos/momi/foto-8.webp',
    video: '',
    corDestaque: '#2B2C1C',
    descricaoCurta: 'O segundo lançamento do Pátio Guarulhos by BP8. Apartamentos de 27 a 46 m², ao lado da futura Estação Dutra de metrô e em frente ao Shopping Internacional Guarulhos. MCMV disponível.',
    descricaoCompleta: 'Após o sucesso de vendas do Residencial Maro, a BP8 apresenta o Residencial Momi. Segundo lançamento dentro do Pátio Guarulhos, complexo com 6 lotes em Itapegica, estrategicamente localizado ao lado da futura Estação Dutra de metrô, em frente ao Shopping Internacional Guarulhos e a poucos minutos do Aeroporto Internacional. 19 itens de lazer e conveniência, lavanderia compartilhada OMO e apartamentos de 27 a 46 m² com financiamento pelo Minha Casa Minha Vida.',
    torres: 2,
    unidades: 468,
    areaLazer: [
      'Piscina Adulto e Infantil',
      'Academia',
      'Fitness Externo',
      'Quadra',
      'Salão de Festas 01',
      'Salão de Festas 02',
      'Coworking',
      'Espaço Gourmet',
      'Churrasqueira 01',
      'Churrasqueira 02',
      'Sports Bar',
      'Sports Bar Externo',
      'Brinquedoteca Kids',
      'Brinquedoteca Baby',
      'Playground',
      'Espaço Pet',
      'Lavanderia Compartilhada',
      'Mini Mercado',
      'Deck'
    ],
    diferenciais: [
      'Segundo lançamento do Pátio Guarulhos by BP8',
      'Ao lado da futura Estação Dutra de metrô',
      'Em frente ao Shopping Internacional Guarulhos',
      'Fácil acesso ao Terminal de Ônibus de Guarulhos',
      'A poucos minutos do Aeroporto Internacional de Guarulhos',
      '19 itens de lazer e conveniência',
      'Minha Casa Minha Vida',
      'Lavanderia compartilhada OMO',
      'Espaço Pet e Espaço Delivery'
    ],
    localizacao: {
      embedUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3659.2428551050903!2d-46.55109997467213!3d-23.487760578850477!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x94ce5f84e39940f5%3A0x6aa97d7e8801230c!2sRua%20Engenheiro%20Camilo%20Olivetti%2056%2C%20Itapegica!5e0!3m2!1spt-BR!2sbr!4v1770049374223!5m2!1spt-BR!2sbr',
      mapsUrl: 'https://maps.app.goo.gl/YHFM6rpfCLvsH2Vg7',
      endereco: 'Av. Carlos Ferreira Endres, s/n - Itapegica. Em frente ao Shopping Internacional Guarulhos',
      mobilidade: 'Ao lado da futura Estação Dutra de metrô, fácil acesso ao Terminal de Ônibus de Guarulhos, à Via Dutra e próximo ao Aeroporto Internacional.',
      bairro: 'Itapegica'
    },
    temMCMV: true,
    plantas: [
      {
        nome: 'Tipo D - Studio',
        area: '27 m²',
        preco: 'R$ 239.418,48',
        avaliacao: 'R$ 268.905,00',
        imagem: 'assets/plantas/momi/planta-tipo-d.webp',
        destaque: false,
        tag: 'Studio',
        slug: 'tipo-d-studio'
      },
      {
        nome: 'Tipo A - 2 Dorms',
        area: '39,53 m²',
        preco: 'R$ 357.000',
        avaliacao: 'R$ 390.500',
        imagem: 'assets/plantas/momi/planta-tipo-a.webp',
        destaque: false,
        tag: '2 Dormitórios',
        slug: 'tipo-a-2-dorms'
      },
      {
        nome: 'Tipo C - 2 Dorms',
        area: '39,16 m²',
        preco: 'R$ 376.584,56',
        avaliacao: 'R$ 380.946,00',
        imagem: 'assets/plantas/momi/planta-tipo-c.webp',
        destaque: true,
        tag: '2 Dormitórios',
        badge: 'Mais vendido',
        slug: 'tipo-c-2-dorms'
      },
      {
        nome: 'Tipo E - 2 Dorms',
        area: '39,16 m²',
        preco: 'R$ 320.178,08',
        avaliacao: 'R$ 337.755,00',
        imagem: 'assets/plantas/momi/planta-tipo-e.webp',
        destaque: false,
        tag: '2 Dormitórios',
        slug: 'tipo-e-2-dorms'
      },
      {
        nome: 'Tipo B - 2 Dormitórios',
        area: '46,40 m²',
        preco: 'R$ 381.246,72',
        avaliacao: 'R$ 425.280,00',
        imagem: 'assets/plantas/momi/planta-tipo-b.webp',
        destaque: false,
        tag: '2 Dormitórios',
        slug: 'tipo-b-2-dorms-suite'
      }
    ],
    galeria: [
      { src: 'assets/fotos/momi/foto-8.webp', caption: 'Fachada' },
      { src: 'assets/fotos/momi/foto-15.webp', caption: 'Portaria' },
      { src: 'assets/fotos/momi/foto-1.webp', caption: 'Piscina' },
      { src: 'assets/fotos/momi/foto-13.webp', caption: 'Piscina (segunda vista)' },
      { src: 'assets/fotos/momi/foto-7.webp', caption: 'Espaço Gourmet' },
      { src: 'assets/fotos/momi/foto-2.webp', caption: 'Churrasqueira Espaço Gourmet' },
      { src: 'assets/fotos/momi/foto-17.webp', caption: 'Salão de Festas 01' },
      { src: 'assets/fotos/momi/foto-18.webp', caption: 'Salão de Festas 02' },
      { src: 'assets/fotos/momi/foto-19.webp', caption: 'Sports Bar' },
      { src: 'assets/fotos/momi/foto-6.webp', caption: 'Coworking' },
      { src: 'assets/fotos/momi/foto-10.webp', caption: 'Academia' },
      { src: 'assets/fotos/momi/foto-9.webp', caption: 'Fitness Externo' },
      { src: 'assets/fotos/momi/foto-16.webp', caption: 'Quadra' },
      { src: 'assets/fotos/momi/foto-14.webp', caption: 'Playground' },
      { src: 'assets/fotos/momi/foto-12.webp', caption: 'Espaço Pet' },
      { src: 'assets/fotos/momi/foto-11.webp', caption: 'Lavanderia' },
      { src: 'assets/fotos/momi/foto-3.webp', caption: 'Brinquedoteca Baby' },
      { src: 'assets/fotos/momi/foto-4.webp', caption: 'Brinquedoteca Kids' },
      { src: 'assets/fotos/momi/foto-5.webp', caption: 'Churrasqueira Externa' }
    ]
  }
];
